# Generated by Django 4.2 on 2025-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('asset_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Fan', 'Fan'), ('Desktop', 'Desktop')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
