# Generated by Django 4.2 on 2025-09-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('round1', models.BooleanField(default=False)),
                ('round2', models.BooleanField(default=False)),
                ('round3', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
