# Generated by Django 5.0.7 on 2025-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0003_company_student_delete_placement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='course_undergone_in_learnmore_technologies',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='shortlisted_candidate_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='placement_date',
        ),
        migrations.AddField(
            model_name='student',
            name='attended_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='final_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='first_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='graduating_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pass_out_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='second_round',
            field=models.BooleanField(default=False),
        ),
    ]
