# Generated by Django 5.0.7 on 2025-09-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Assets.company'),
        ),
    ]
