# Generated by Django 5.0.7 on 2025-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0008_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimbursed',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, verbose_name='Reimbursed (Paid back to employee)'),
        ),
    ]
