# Generated by Django 6.0.7 on 2026-08-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0009_expense_reimbursed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
