# Generated by Django 6.0.7 on 2026-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0013_customrole_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Approval Status'),
        ),
    ]
