# Generated by Django 6.0.7 on 2026-08-11 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0014_expense_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecaller_name', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('OUTGOING', 'Outgoing'), ('INCOMING', 'Incoming'), ('MISSED', 'Missed')], default='OUTGOING', max_length=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('audio_file', models.FileField(upload_to='call_recordings/%Y/%m/%d/')),
                ('call_timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('telecaller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
